name: Daily R Script Run

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow every day at midnight UTC
  workflow_dispatch:  # This allows you to manually trigger the workflow from GitHub

jobs:
  run_r_script:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This checks out your code from the GitHub repository

      - name: Set up R
        uses: r-lib/actions/setup-r@v2  # This sets up R on the runner environment
        with:
          r-version: '4.2'  # You can specify the R version you need

      - name: Install dependencies
        run: |
          install.packages(c("atrrr", "readxl", "writexl"))  # Install R packages required by your script

      - name: Run R script
        run: |
          Rscript main.R   
