name: Daily R Script Run
on:
  schedule:
    - cron: '45 6 * * *'  # Fixed: was missing one *
  workflow_dispatch:

jobs:
  run_r_script:
    runs-on: ubuntu-20.04  # Pin to Ubuntu 20.04 temporarily
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4
        with:
          fetch-depth: 0
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          
      - name: Fix DNS resolution
        run: |
          # Add DNS servers to resolve bsky.social endpoints
          echo "nameserver 8.8.8.8" | sudo tee -a /etc/resolv.conf
          echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf
          # Test DNS resolution
          nslookup bsky.social || echo "DNS resolution test failed"
          
      - name: Install R packages
        run: |
<<<<<<< HEAD
          R -e 'install.packages(c("remotes", "jsonlite", "httr2", "readxl", "writexl", "dplyr"), repos = "https://cloud.r-project.org/")'
          R -e 'remotes::install_version("curl", version = "4.3.2", repos = "https://cloud.r-project.org")'
          R -e 'install.packages("atrrr", repos = "https://cloud.r-project.org")'
=======
          R -e 'install.packages(c("curl", "jsonlite", "httr2", "atrrr", "readxl", "writexl","dplyr"), repos="https://cloud.r-project.org/")'
>>>>>>> parent of 43d3c97 (Fix curl version)
          
      - name: Run R script
        run: Rscript main.R
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          
      - name: Network debugging
        run: |
          echo "=== Network Configuration ==="
          cat /etc/resolv.conf
          echo "=== DNS Resolution Tests ==="
          nslookup bsky.social || echo "bsky.social resolution failed"
          nslookup public.api.bsky.app || echo "public.api.bsky.app resolution failed"
          echo "=== Connectivity Tests ==="
          curl -I https://bsky.social || echo "bsky.social connectivity failed"
          curl -I https://public.api.bsky.app || echo "public.api.bsky.app connectivity failed"
          
      - name: Delay to ensure files are ready
        run: sleep 5  
        
      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes to commit
          if [[ -n "$(git status --porcelain)" ]]; then
            git add bsky_followers.xlsx bsky_posts.xlsx
            git commit -m "Update followers and posts data [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}