name: Daily R Script Run

on:
  schedule:
    - cron: '45 6 * * *'  # Runs daily at 6:45 AM UTC
  workflow_dispatch:

jobs:
  run_r_script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev

      - name: Install R packages
        run: |
          R -e 'install.packages(c("curl", "jsonlite", "httr2", "atrrr", "readxl", "writexl"), repos="https://cloud.r-project.org/")'
          
      - name: Run R script
        run: Rscript main.R
        
      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if there are changes to commit
          if [[ -n "$(git status --porcelain)" ]]; then
            git add bsky_followers.xlsx bsky_posts.xlsx
            git commit -m "Update followers and posts data [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
